### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by rhysperry111** [eworm-de/mkinitcpio-archlogo#2]
Sorry if I have missed something obvious, but I have installed the package from the AUR yet I see no logo on boot. There aren't any instructions in the README so I am not quite sure what I need to do.

**Comment by rhysperry111** [comment]
Fixed it myself. Will make a PR with suggested changes to README

**Comment by eworm-de** [comment]
On package installation you should have read this info:

> Now add 'archlogo' to your HOOKS array in /etc/mkinitcpio.conf
> and rebuild initial ramdisk.
> You can put your own artwork in /usr/share/archlogo/ and select
> a non-default one in /etc/archlogo.conf.
